### ISSUE TITLE
Server Pack cannot be installed

### ISSUE THREAD

**Issue by Tunanodra** [ReeCodes/ER-Ponders#1]
I download the server pack, and double click the install.bat file, But it didn't work at all, it cannot reach the URL of mods

**Comment by Tunanodra** [comment]
[ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=370777, fileID=3211052)

It always shows this

**Comment by ReeCodes** [comment]
Hey, I just looked up the file your unable to download which is:
https://www.curseforge.com/minecraft/mc-mods/scaffolding-behavior/files/3211052

But I don't understand why that would be the case, since it has not been removed from CF.
